#pragma once
#include <functions.h>

#ifndef DAMAGETABLE_H
#define DAMAGETABLE_H

typedef enum {
    DMGEFF_DEKU_NUT,
    DMGEFF_DEKU_STICK,
    DMGEFF_SLINGSHOT,
    DMGEFF_EXPLOSIVE,
    DMGEFF_BOOMERANG,
    DMGEFF_ARROW,
    DMGEFF_HAMMER_SWING,
    DMGEFF_HOOKSHOT,
    DMGEFF_SWORD_KOKIRI,
    DMGEFF_SWORD_MASTER,
    DMGEFF_SWORD_KNIFE,
    DMGEFF_ARROW_FIRE,
    DMGEFF_ARROW_ICE,
    DMGEFF_ARROW_LIGHT,
    DMGEFF_ARROW_UNKNOWN_1,
    DMGEFF_ARROW_UNKNOWN_2,
    DMGEFF_ARROW_UNKNOWN_3,
    DMGEFF_MAGIC_FIRE,
    DMGEFF_MAGIC_ICE,
    DMGEFF_MAGIC_LIGHT,
    DMGEFF_SHIELD,
    DMGEFF_MIRROR_RAY,
    DMGEFF_SWORD_SPIN_KOKIRI,
    DMGEFF_SWORD_SPIN_KNIFE,
    DMGEFF_SWORD_SPIN_MASTER,
    DMGEFF_SWORD_JUMP_KOKIRI,
    DMGEFF_SWORD_JUMP_KNIFE,
    DMGEFF_SWORD_JUMP_MASTER,
    DMGEFF_UNKNOWWN_1,
    DMGEFF_UNBLOCKABLE,
    DMGEFF_HAMMER_JUMP,
    DMGEFF_UNKNOWN_2,
} DamageEntries;

DamageTable rogueLikeEnemyDamageTable;
DamageTable GetModifiedDamageTable(Actor* refActor);

#endif DAMAGETABLE_H
