name: pr-artifacts

on:
  workflow_run:
    workflows: [generate-builds]
    types:
      - completed

jobs:
  pr-artifacts:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - id: 'pr-number'
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const prNumber = await (async () => {
              const pulls = await github.pulls.list({owner, repo});
              for await (const {data} of github.paginate.iterator(pulls)) {
                for (const pull of data) {
                  if (pull.head.sha === pull_head_sha && pull.user.id === pull_user_id) {
                    return pull.number;
                  }
                }
              }
            })();

            if (!prNumber) {
              return core.error(`No matching pull request found`);
            }

            return prNumber;
      - id: 'artifacts-text'
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });

            return allArtifacts.data.artifacts.reduce((acc, item) => {
              if (item.name === "assets") return acc;
              acc += `
              - [${item.name}](${context.payload.repository.html_url}/suites/${context.payload.workflow_run.check_suite_id}/artifacts/${item.id})`;
              return acc;
            }, '### Build Artifacts');
      - id: 'add-to-pr'
        uses: garrettjoecox/pr-section@3.1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          pr-number: ${{ steps.pr-number.outputs.result }}
          section-name: 'artifacts'
          section-value: '${{ steps.artifacts-text.outputs.result }}'
